language: node_js
node_js:
- stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
- sed -i "s/\/master\//\/$TRAVIS_BRANCH\//g" README.md # replace "master" in doc urls with current branch/tag
- npm run doc
after_success:
- jsdoc/publish.sh
env:
  global:
    secure: Bx6pW0ihp3Y2dW5a8fkPhbMKsVg7MRfCzN3laN/OL7vTy2etIDXFleddE5No74HVQ1gPhkOIoRko/pHPdzWGNq69VtoCxp3AdISsuillYcaDCfRXDBSZXbHVuXsUHFQIABIdKJZZVjjwXM4oulL4OWboZ8FWV7vgOBvN4ZrXjM8LfuahSG51cPbPktqa+v/rA03iuWwC8IUDhf5w2uNPrsvtzWmj+CHcpLIgjmJWan+SiJXK/i3Wz/B74Cb0RtP9Y7zJzIGSWg8Z1VruN/f8xoNeSbMz5HM+PMhGyQJ9QXUNEqUEiXG+gwIzhAYRwBbCGyQZME5zk/y7QM0lr3/4NBzq8e6RYWlyOVLRGxlL6SvPmQ/6FrMCe9QDcMnvDvfeYhTHa6SnkqymN1hp1JnPC65zXENbEOLJH/67mQs/WoHLuuZycUK0KPC+GK6Bc45ViXotyNTttzrxHfpOV4IXQDVqB6p6tlh940ksYpetSs+8s7piUOGIcu4XtYxdnSRGX7TwKiCuuK65XWYpk+oMWhKHsOS2FTDt85+PXKFnM1fiuFD+Oppa7xyXmSUZp4C1befd7nP7F5RGSkZWdfXuCY6xAS6E7dho4clIua2yhOWtgnoMlcjjht6sFYf8OEk3eoVvnP+OO3VSHwk0VkTbI3E3fp3H8CUXVMk9woegydQ=
before_deploy:
- npm run build
deploy:
- provider: releases
  api_key:
    secure: H5ykqiOnawQxu/tjHtEKAWy2BivWD3gZI8EljVejqQO+kJLcDqJA6qjj1cCQ6kNHoEgAW8se0F9EXGpIpDt8w0Bj7t0hpzT+F/zVvAhWFTKoheugQzkvIrZzBQH1Szg2I25O1PR+f5jwu1vpnPNiu2axU85hIF8eHiscwwHd7UuD7kyGHFEBqiGp+mSDhrwMeEGDdpiojN8uHd2YFFDRZPCqdu+Sft7Y0PmUMFpMSmqQ9pttYDf27K9jowYcT7Qh8XCjX+3p/RXQcSQM6gp4mRo9bcYhPTcZeA0S5Bo/yiDE9QfiD6+pj7u6yGJG8yDZouiVwclA0Pjaf9ntjW1aKNeqBthYfxYq0XJ9Ac3GJvwdQm2lbcsvHFrr106yNlJCHrRd3CiW34MfPn+RrjmEjPMYzGYd1qEEbyAEx/oA6g7LCi/f3ZwQPBsrr9ChhdsfyCvTDzwz5NpxuV2ybqLL4fEGMJdIuFmGUlVWKhbsBZouPFsFz5FTDdHsap+s4WErpQXmUv69zC9ueQOPyRdNzRw6mnN0n4pFXJiIWcolCiK5wUjbUITD6rfvUd4U/4jU0YAk824nivlesTWInmQSTmYvQWi6XJ+LX8XxJwGf4Vw8qJc66RKP+Y2mNyvQu2uUebT1TObY6VhMYGj2gYi+pVzc9NyD25U//8JxgIt1b2c=
  file:
  - dist/watson-speech.js
  - dist/watson-speech.min.js
  skip_cleanup: true
  on:
    tags: true
    repo: watson-developer-cloud/speech-javascript-sdk
- provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: SPayKFCZfsEznCkOuH/tX9R1ZmtZZ98JkPOv6AiVatGrFIsAx0WWQWyebx1X9dvtxznTwslP0u/nv+i5ErtMdjutyhylz/rwJ7v1s0vR8+4E8JpnPOIOHX1YWybCz38N6u7Ue6+Km4AxmtnTeEhfChn3R4qgJK3qlit8GRxpOlBzUWDFbUYHz6TZOn3YnU2i1bruxcWLwfwXs0Pef1tIZrNC3LrvqpU39REX+vAFMSCTN+1F7u/Aax+zSp2POJkbpV9ijVXtQiNW643Di8XkaeGedzt7L/VtNG+6iJ//fqpULwYktTSdlNzwvNdu8IJ70VmhTOxVWWTcBlJOQNkjHXcU/E3N7keieQo7yE1dWoignNqUrTOaQIOnLxbmfjWAsRsieMSPNRIRvboXJfA5oppZ5lhfiAkyfJV8rNzc9Yt+KWO9uLbdfYJjok7CnICzlPhn2Ho7NHpfqLpJiT/V52C8I0UDMEDBMxCDee2/zHqoTJzzdJpbsGG/6LaEiLoO6+GWnreeBLlPSCE3GmIB1sJGaqJ7Zyfo0/LdTnCM+R2QHh1ju4YGLk8EKsSYfmlDRuat+qCstjOAEmpz3OmJENRAmTMHDkyaPL5v0RuR4S9uN/mlvAEPhSn4w4CZwuWLEpHolG4Zb7ltTgTsE6k4NpWUo2tx/uSb/D4cVzWB4u4=
  skip_cleanup: true
  on:
    tags: true
    repo: watson-developer-cloud/speech-javascript-sdk
